version: "3.8"

services:
  postgres:
    container_name: setup_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=setupDev
      - POSTGRES_USER=setup
      - POSTGRES_DB=setup
    ports:
      - "5432:5432"
    #volumes:
    # - ./pgdata:/var/lib/postgresql/data
    networks:
      - setup_network

networks:
  setup_network:
    driver: bridge
